# Generated by Django 5.2 on 2025-04-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_modeldata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelData',
        ),
    ]
