# Generated by Django 5.2 on 2025-04-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_delete_modeldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField()),
            ],
        ),
    ]
