# Generated by Django 5.2 on 2025-05-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_modeldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='iChairData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termCode', models.CharField(max_length=100)),
                ('termNum', models.CharField(max_length=100)),
                ('crn', models.CharField(max_length=100)),
            ],
        ),
    ]
